version: '3.0'

networks:
  weather:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  weather-bot:
    image: webbnba/weather-bot:latest
    ports:
      - "8086:8086"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOST=postgres:5432
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - weather
    depends_on:
      - postgres
      - open-weather

  open-weather:
    image: webbnba/open-weather:latest
    ports:
      - "8085:8085"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    networks:
      - weather

  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5437:5432"
    env_file:
      - .env
    networks:
      - weather
    volumes:
      - db-data:/var/lib/postgresql/data