create table requests
(
    id           bigint generated by default as identity primary key,
    command      varchar(36)  not null,
    timestamp    timestamp    not null default current_timestamp,
    payload      jsonb
);